---
x-devenv-common:
  &devenv-common
  env_file:
      - .env
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - "${WEBAPP_DIRECTORY}:/var/www/html"
    - "./etc/apache:/etc/apache2/sites-available"
  environment:
    APACHE_HOST_PORT: "80"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_RANDOM_ROOT_PASSWORD: "no"
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_DATABASE: "${DB_USER}"
    MYSQL_USER: "${DB_USER}"
    MYSQL_PASSWORD: "${DB_USER}"

services:
  web:
    <<: *devenv-common
    ports:
      - "${WEBAPP_EXPOSED_PORT}:${APACHE_HOST_PORT}"
    command: bash -c "a2enmod headers && a2enmod rewrite && apache2ctl -D FOREGROUND"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # depends_on:
    #   db:
    #     condition: service_healthy


  # db:
  #   <<: *devenv-common
  #   image: mysql:5.7.33
  #   ports:
  #     - "${DB_EXPOSED_PORT}:3306"
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 30s
    